jeffreypullin/rater

- R/extract.R
- R/inference.R
- R/models.R
- R/rater_model_class.R
Unlike the last implementation this one reuses the Dawid-skene stan
model and does not add support for 'multinomial data' though that may be
added later.
> Add the homogenous dawid-skene (multinomial) model

- R/extract.R
- tests/testthat/test_fit_class.R
- tests/testthat/test_plotting.R
> Fix remaining 'prevalance' typos

- DESCRIPTION
With this there is nothing blocking us from submitting to CRAN!
> Bump rstantools to CRAN 2.0.0

- DESCRIPTION
> Fix github links

- R/data_types.R
Note that the error only occurred when: 
`Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = "TRUE")`
> Use inherits not class

- DESCRIPTION
- R/rater_fit_class.R
- R/utils.R
- man/anesthesia.Rd
- man/caries.Rd
- man/extract_pi.mcmc_fit.Rd
- man/extract_pi.optim_fit.Rd
- man/plot.rater_fit.Rd
- tests/testthat/test_fit_class.R
> Use pars plot

- R/inference.R
- tests/testthat/test_rater.R
Also added a test to detect large changes in the results in future.
> Fix bug changing inference results

- R/inference.R
- R/plotting.R
- R/rater-package.R
- R/rater_fit_class.R
- inst/stan/grouped_data.stan
- man/plot_pi.Rd
- man/rater-package.Rd
- man/rater.Rd
This fixes a few things, including fixing #82
> Fix some typos and bugs

- R/inference.R
- man/rater.Rd
> Add the ability to pass model as a string

- R/extract.R
- R/inference.R
- R/rater_fit_class.R
- tests/testthat/setup.R
- tests/testthat/test_extract.R
and use it in the extraction functions.
Fixes #79
> Retain stan data information after fitting

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
> Fix Github Actions

- R/extract.R
- R/inference.R
- R/rater_fit_class.R
- man/class_probabilities.Rd
- man/mcmc_diagnostics.Rd
- man/plot.rater_fit.Rd
- man/point_estimate.Rd
- man/posterior_interval.mcmc_fit.Rd
- man/posterior_samples.Rd
- man/rater.Rd
To improve the look of the pkgdown website.
> Remove spaces before \dontrun

- R/data.R
- man/anesthesia.Rd
- man/caries.Rd
> Improve dataset documentation

- R/inference.R
- tests/testthat/test_rater.R
This uses the *mean* matched derivation of the prior with the values:
N = 7
p = 0.64
Fixes #110
> Update default prior on beta

- NEWS.md
- R/rater_fit_class.R
> Fix number of remaining parameters displayed

- NEWS.md
- R/inference.R
- tests/testthat/test_rater.R
cc @dvukcevic 
This changes the parameters to N = 8, p = 0.6.
> Tweak prior parameters

- DESCRIPTION
- tests/testthat/test_extract.R
- tests/testthat/test_fit_class.R
- tests/testthat/test_model_class.R
- tests/testthat/test_models.R
- tests/testthat/test_plotting.R
- tests/testthat/test_rater.R
- tests/testthat/test_utils.R
Also update tests to deal with testthat 3rd edition and R devel (4.1?)
now checking enviroments
Fixes #123 
These changes fix the problem on R-devel
> Update to testthat 3rd edition

- NEWS.md
- R/inference.R
- R/models.R
- inst/stan/dawid_skene.stan
- inst/stan/grouped_data.stan
- tests/testthat/test_models.R
- tests/testthat/test_rater.R
Fixes #126 
See the new NEWS entry for details.
cc @Agasax - sorry this took so long, I didn't manage to finish it before my holidays. If you have time to test this branch sometime soon that would be fantastic but no worries it not.
(P.S. FYI I am aware that rater has gone off CRAN and am working to get it back on with these new features ASAP)
> Rater specific priors

- R/inference.R
- R/mcmc_diagnostics.R
- R/models.R
- R/posterior_samples.R
- R/rater_fit_class.R
- tests/testthat/_snaps/mcmc_diagnostics.md
- tests/testthat/_snaps/model_class.md
- tests/testthat/_snaps/point_estimate.md
- tests/testthat/_snaps/posterior_interval.md
- tests/testthat/_snaps/posterior_predict.md
- tests/testthat/_snaps/posterior_samples.md
- tests/testthat/_snaps/rater.md
- tests/testthat/helper.R
- tests/testthat/setup.R
- tests/testthat/test-data_format.R
- tests/testthat/test-mcmc_diagnostics.R
- tests/testthat/test-model_comparison.R
- tests/testthat/test-point_estimate.R
- tests/testthat/test-posterior_interval.R
- tests/testthat/test-posterior_predict.R
- tests/testthat/test-posterior_samples.R
- tests/testthat/test_fit_class.R
- tests/testthat/test_model_class.R
- tests/testthat/test_models.R
- tests/testthat/test_plotting.R
- tests/testthat/test_rater.R
- tests/testthat/test_utils.R
Also some small changes to code
> Refresh tests and add many more

- DESCRIPTION
Hi @Agasax,
This PR adds you as an author to rater. Thank you very much for your contribution!
Before I merge this could you just check whether you are happy with how I have split up your three names into `"given"` and `"family"`; I'm very happy to change it if I've got it the wrong way round. 
Best, 
Jeffrey
> Add Lars as a package author

- R/posterior_predict.R
- tests/testthat/test-posterior_predict.R
As identified by the JSS editor
> Fix bug in validation of rater in posterior_predict

- R/inference.R
- R/mcmc_diagnostics.R
- R/point_estimate.R
- R/posterior_samples.R
- R/rater_fit_class.R
- tests/testthat/_snaps/mcmc_diagnostics.md
- tests/testthat/_snaps/point_estimate.md
- tests/testthat/_snaps/posterior_interval.md
- tests/testthat/_snaps/posterior_samples.md
- tests/testthat/test-mcmc_diagnostics.R
- tests/testthat/test-point_estimate.R
- tests/testthat/test-posterior_interval.R
- tests/testthat/test-posterior_samples.R
- tests/testthat/test_plotting.R
- tests/testthat/test_rater.R
> Return theta from the hierarchical Dawid-Skene model

- R/plotting.R
- R/rater_fit_class.R
- man/plot.rater_fit.Rd
- tests/testthat/test_plotting.R
Interface:
```r
plot(fit, pars = "theta", theta_plot_type = "points", rater_index = 1)
```
> Add new visualisation of theta uncertainty
